name: main-test

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hexlet project test with flake8 (hard wsp)
        run: make lint
